
/*	var vocabulary = [
	"a","i","k","u","y","ai","am","an","as","at",
  "be","by","dj","do","eh","eq","ew","go","ha","he",
  "hi","if","in","is","it","jk","me","my","no","of",
  "oh","ok","on","or","so","to","thank you","up","us","we",
  "ya","aah","act","add","age","all","and","any","are","ask",
   "bad","big","bit","biz","box","but","buy","can","cdj","cry",
  "cut","day","dev","dry","eat","end","eye","faq","fat","few",
  "fit","fix","fly","for","gap","get","god","her","him","his",
  "how","ifs","its","job","joy","key","kit","law","lie","lol",
  "man","map","max","mix","may","net","new","nil","not","now",
  
  "off","one","out","own","pad","pen","pin","qua","rig","say",
  "see","she","sky","the","tie","too","top","try","two","ups",
  "use","vet","vox","was","way","web","who","why","win","ecstasy",
  "xxx","yes","yet","you","zen","away","base","back","bare","best",
  "bite","both","burn","call","care", "case","coin","cool","cost","down",
  "draw","drop","dust","each","earn","else","even","ever","exec","face",
  "fail","fear","feel","fill","first","fold","form","from","fund","game",
  "gift","give","good","grow","hand","hate","have","help","hold","hope",
  "hurt","idle","join","jump","just","keep","kill","know","land","last",
  "lead","like","list","lock","lose","love","make","many","mark","mean",
	
	"meet","mind","miss","more","most","move","name","near","need","only",
  "open","over","pair","part","pass","pull","push","quit","read","rest",
  "ride","rule","rush","said","save","shop","show","slow","some","stay",
  "step","stop","such","take","talk","tell","test","than","that","then",
  "they","this","tool","true","turn","type","undo","very","view","wait",
   "walk","want","were","what","when","will","with","wire","word","work",
  "xing","yall","zero","about","above","after","again","along","angle","block",
  "board","break","build","carry","catch","chase","class","clean","clear","climb",
  "close","count","cover","crash","cross","dance","dirty","dream","drive","empty",
  "equal","exact","fault","fever","fight","floor","force","front","group","hurry",
  
  "issue","judge","known","leave","light","lower","model","never","offer","order",
  "other","paper","party","people","piece","place","plane","plant","point","power",
  "press","price","prize","quiet","quota","reach","reply","right","round","serve",
  "shade","shake","shape","share","shine","short","shout","small","sound","space",
  "spend","stand","start","still","study","taste","their","there","think","title",
  
  "total","touch","trust","voice","visit","waste","watch","water","where","which",
  "woman","worry","would","write","wrong"
  ];

*/

var vocabulary = [
	"as a ",
	"about ",
	"actually ",
	"add ",
	"as ever ",
	"as for ",
	"again ",
	"as held ",
	"ai ",
	"also just ",
	"aka ",
	"all ",
	"amount ",
	"any ",
	"as of ",
	"application ",
	"a question ",
	"area ",
	"as ",
	"at ",
	"any use ",
	"avoid ",
	"away ",
	"acts ",
	"as you ",
	"above zero ",
	"back ",
	"be back ",
	"because ",
	"big deal ",
	"being ",
	"before ",
	"begin ",
	"behind ",
	"big ",
	"bad job ",
	"block ",
	"be all ",
	"bpm ",
	"been ",
	"bored ",
	"bump ",
	"being questioned ",
	"bring ",
	"be sure ",
	"be there ",
	"back up ",
	"believe ",
	"backward ",
	"box ",
	"by ",
	"business ",
	"see as ",
	"can be ",
	"collect ",
	"could ",
	"chance ",
	"can if ",
	"change ",
	"check ",
	"can i ",
	"can just ",
	"see ok ",
	"call ",
	"see them ",
	"seeing ",
	"company ",
	"copy ",
	"can question ",
	"see our ",
	"see us ",
	"cute ",
	"see you ",
	"cover ",
	"can we ",
	"cross ",
	"can you ",
	"crazy ",
	"does a ",
	"do be ",
	"direct ",
	"data ",
	"do every ",
	"do for ",
	"do get ",
	"duh ",
	"did ",
	"do justice ",
	"do know ",
	"deal ",
	"do mean ",
	"done ",
	"do over ",
	"depend ",
	"disqualified ",
	"doctor ",
	"does ",
	"do that ",
	"do you ",
	"divide ",
	"down ",
	"derivative ",
	"do you ",
	"divide by zero ",
	"each ",
	"everybody ",
	"exchange ",
	"edit ",
	"everything else ",
	"effect ",
	"edge ",
	"ever had ",
	"else if ",
	"ever just ",
	"ever know ",
	"except like ",
	"emotion ",
	"end ",
	"everyone ",
	"episode ",
	"equal ",
	"error ",
	"ever said ",
	"either ",
	"except you ",
	"ever ",
	"everywhere ",
	"extra ",
	"every ",
	"easy ",
	"fact ",
	"fabricate ",
	"face ",
	"find ",
	"iron ",
	"fast forward ",
	"forget ",
	"for them ",
	"faithful ",
	"for justice ",
	"freak ",
	"file ",
	"form ",
	"function ",
	"for ",
	"flip ",
	"frequent ",
	"from ",
	"fast ",
	"front ",
	"freaky ",
	"favorite ",
	"forward ",
	"effects  ",
	"for you ",
	"freeze ",
	"good at ",
	"goodbye ",
	"grace ",
	"god ",
	"get ",
	"gift ",
	"go get ",
	"go home ",
	"got it ",
	"good job ",
	"goot to know ",
	"glad ",
	"get me ",
	"gone ",
	"game over ",
	"good part ",
	"good ",
	"get real ",
	"guess ",
	"great ",
	"give up ",
	"give ",
	"grow ",
	"get access ",
	"got you ",
	"got zero ",
	"l o l ",
	"had been ",
	"how can ",
	"had ",
	"they ",
	"half ",
	"hug ",
	"huh ",
	"hello ",
	"had just ",
	"hack ",
	"hold ",
	"hmm ",
	"had now ",
	"hang out ",
	"help ",
	"hq ",
	"hard ",
	"has ",
	"hot ",
	"hang up ",
	"have ",
	"how ",
	"hacks ",
	"happy ",
	"horizon ",
	"is anyone ",
	"i be ",
	"i see ",
	"i do ",
	"is everyone ",
	"if ",
	"ignore ",
	"i hope ",
	"is it ",
	"i just ",
	"i know ",
	"i love ",
	"i am ",
	"in ",
	"instead of ",
	"input ",
	"in question ",
	"in real ",
	"is ",
	"it ",
	"is unless ",
	"invite ",
	"i want ",
	"in time ",
	"if you ",
	"if zero ",
	"just a ",
	"just be ",
	"just because ",
	"just do ",
	"  jesus  ",
	"just for ",
	"just go ",
	"just had ",
	"just in ",
	"just joking ",
	"just kidding ",
	"just like ",
	"just me ",
	"just now ",
	"job ",
	"jump ",
	"just ",
	"just right ",
	"just so ",
	"just that ",
	"just us ",
	"just very ",
	"just w ",
	"just x ",
	"just you ",
	"just zero ",
	"known as ",
	"kept back ",
	"knack ",
	"kidding ",
	"knew ",
	"known for ",
	"king god ",
	"know how ",
	"know if ",
	"know just ",
	"ok ok ",
	"know like ",
	"know more ",
	"know ",
	"knockout ",
	"kind people ",
	"ok quit ",
	"know right ",
	"know something ",
	"know that ",
	"kit up ",
	"know very ",
	"know what ",
	"kind kind ",
	"ok why ",
	"keep zero ",
	"last ",
	"lets be ",
	"lucky ",
	"loud ",
	"less ",
	"life ",
	"let go ",
	"love how ",
	"love it ",
	"like just ",
	"like ",
	"less like ",
	"lame ",
	"like now ",
	"low ",
	"lets play ",
	"lets quit ",
	"learn ",
	"lets say ",
	"love to ",
	"like us ",
	"love ",
	"law ",
	"ex ",
	"love you ",
	"lazy ",
	"matter ",
	"might be ",
	"my choice ",
	"made ",
	"me ",
	"maybe if ",
	"my god ",
	"my head ",
	"mind ",
	"major ",
	"make ",
	"my love ",
	"my man ",
	"man ",
	"monster ",
	"map ",
	"mmm ",
	"more ",
	"miss ",
	"empty ",
	"music ",
	"move ",
	"my way ",
	"max ",
	"made you ",
	"maze ",
	"not applicable ",
	"noob ",
	"nice ",
	"no deal ",
	"any ",
	"not found ",
	"not gonna ",
	"not happy ",
	"not if ",
	"nice job ",
	"not known ",
	"not like ",
	"never mind ",
	"not now ",
	"no ",
	"no problem ",
	"not quite ",
	"not really ",
	"not so ",
	"nice try ",
	"not until ",
	"not very ",
	"now ",
	"no no no ",
	"not yet ",
	"noise ",
	"on arrival ",
	"object ",
	"original content ",
	"overdose ",
	"once ",
	"of ",
	"original ",
	"oh ",
	"on it ",
	"one job ",
	"ok ",
	"overload ",
	"on me ",
	"on ",
	"uh oh ",
	"oppose ",
	"or quit ",
	"or ",
	"our side ",
	"off topic ",
	"oh you ",
	"over ",
	"ow ",
	"kiss ",
	"u wot mate ",
	"over zero ",
	"past ",
	"phobia ",
	"place ",
	"put down ",
	"people ",
	"perf ",
	"page ",
	"phone ",
	"put it ",
	"people just ",
	"please know ",
	"please ",
	"prime ",
	"plan ",
	"pretty old ",
	"pretty please ",
	"may i ",
	"price ",
	"ps ",
	"part time ",
	"pick up ",
	"pov ",
	"power ",
	"pvp ",
	"pay ",
	"prize ",
	"quality ",
	"cube ",
	"control ",
	"quad ",
	"quine ",
	"faq ",
	"quite good ",
	"quoth ",
	"qi ",
	"quit joking ",
	"quick ",
	"qualify ",
	"qualm ",
	"question ",
	"quote ",
	"quip ",
	"quick question ",
	"queer ",
	"queues ",
	"quit ",
	"qua ",
	"quite valuable ",
	"qwerty ",
	"exquisite ",
	"quit you ",
	"q ",
	"raw ",
	"right back ",
	"race ",
	"read ",
	"regarding ",
	"real funny ",
	"rage ",
	"right how ",
	"read it ",
	"right just ",
	"rank ",
	"real ",
	"remove ",
	"right now ",
	"romance ",
	"role play ",
	"request ",
	"reread ",
	"research ",
	"realtime ",
	"are you ",
	"reveal ",
	"rewrite ",
	"recommend ",
	"ready ",
	"reason ",
	"such as ",
	"email ",
	"scary ",
	"side ",
	"select ",
	"self ",
	"signal ",
	"shine ",
	"yes ",
	"so just ",
	"skip ",
	"soul ",
	"small ",
	"should not ",
	"so ",
	"space ",
	"square ",
	"senior ",
	"serious ",
	"saint ",
	"superuser ",
	"save ",
	"software ",
	"sucks ",
	"seriously ",
	"s ",
	"think about ",
	"to be ",
	"take care ",
	"to do ",
	"only you ",
	"too far ",
	"to go ",
	"think ",
	"that is ",
	"they just ",
	"take ",
	"tool ",
	"to me ",
	"to not ",
	"take over ",
	"to please ",
	"to question ",
	"try ",
	"to show ",
	"talk to ",
	"to us ",
	"the internet ",
	"twice ",
	"transmit ",
	"thank you ",
	"time zone ",
	"you are ",
	"you bet ",
	"you see ",
	"you do ",
	"you expect ",
	"you forgot ",
	"you got ",
	"you have ",
	"you insist ",
	"you just ",
	"you know ",
	"unless ",
	"you might ",
	"you need ",
	"you ought to ",
	"up ",
	"unquestionable ",
	"you really ",
	"us ",
	"until ",
	"unuseable ",
	"unavailable ",
	"you want ",
	"unexpected ",
	"unity ",
	"use ",
	"value ",
	"very best ",
	"very cool ",
	"video ",
	"verity ",
	"vilified ",
	"video game ",
	"vanish ",
	"six ",
	"very jealous ",
	"very kind ",
	"volume ",
	"virtual machine ",
	"very nice ",
	"very obvious ",
	"very pretty ",
	"vanquish ",
	"virtual reality ",
	"versus ",
	"vertical ",
	"virtue ",
	"vivid ",
	"view ",
	"vox ",
	"very ",
	"advise ",
	"want ",
	"would be ",
	"we could ",
	"we do ",
	"we ",
	"we find ",
	"wing ",
	"who ",
	"with ",
	"we just ",
	"we know ",
	"would ",
	"warm ",
	"win ",
	"without ",
	"warp ",
	"we quit ",
	"write ",
	"was ",
	"what ",
	"with you ",
	"wave ",
	"worldwide ",
	"we expect ",
	"way ",
	"wise ",
	"extra ",
	"exabytes ",
	"excite ",
	"excited ",
	"exception ",
	"x factor ",
	"extinguish ",
	"exhaust ",
	"exit ",
	"extremists ",
	"seed ",
	"extra large ",
	"station ",
	"fiction ",
	"exotic ",
	"experience ",
	"excused ",
	"xray ",
	"extra small ",
	"ecstasy ",
	"except you ",
	"excessive ",
	"manager ",
	"explicit ",
	"except why ",
	"excise ",
	"years ago ",
	"why be ",
	"why care ",
	"why do ",
	"awake ",
	"you forgot ",
	"why get ",
	"why have ",
	"why i ",
	"why just ",
	"why keep ",
	"why lose ",
	"why i am ",
	"why any ",
	"why only ",
	"why people ",
	"why question ",
	"your ",
	"yours ",
	"yours truly ",
	"why you ",
	"why i have ",
	"why we ",
	"why explain ",
	"yearly ",
	"years ",
	"zero assets ",
	"zero blame ",
	"zero choice ",
	"zero division ",
	"zero equals ",
	"zero favors ",
	"zero guesses ",
	"zero help ",
	"zero ignorance ",
	"zero justice ",
	"zero dark thirty ",
	"zero loss ",
	"zero money ",
	"zone ",
	"zero opportunity ",
	"zero permission ",
	"zero questions ",
	"zero ",
	"zero shame ",
	"zero time ",
	"zero use ",
	"zero views ",
	"zero work ",
	"zero exceptions ",
	"zero pay ",
	"zzz "
];

var synth = window.speechSynthesis;
var synthvoice = synth.getVoices()[1];
function synthpulse() {
		var varray = new Uint16Array(1);
		var vcode = Math.floor(Math.random()*256*256);
		if(vcode<(6760)){
			var utterance = new SpeechSynthesisUtterance(vocabulary[vcode%676]);
			utterance.pitch = (2 * vcode / 6760);
			utterance.voice = synth.getVoices()[1];
			synth.cancel();
			synth.speak(utterance);
		
			
			
		}
};



